// Generated by CoffeeScript 1.7.1
var URL, passThrough, recorded;

passThrough = require("./pass_through");

URL = require("url");

recorded = function(settings) {
  var capture, catalog;
  catalog = settings.catalog;
  capture = passThrough(true);
  return function(request, callback) {
    var host, matcher, matchers, response, _i, _len;
    if (typeof request.url === 'string') {
      request.url = URL.parse(request.url);
      request.path = request.url.path;
    }
    host = request.url.hostname;
    if (request.url.port && request.url.port !== "80") {
      host += ":" + request.url.port;
    }
    matchers = catalog.find(host);
    if (matchers) {
      for (_i = 0, _len = matchers.length; _i < _len; _i++) {
        matcher = matchers[_i];
        response = matcher(request);
        if (response) {
          callback(null, response);
          return;
        }
      }
    }
    if (settings.isIgnored(request.url.hostname)) {
      callback(null);
      return;
    }
    if (settings.mode === "record") {
      capture(request, function(error, response) {
        if (error) {
          return callback(error);
        }
        return catalog.save(host, request, response, function(error) {
          return callback(error, response);
        });
      });
      return;
    }
    return callback(null);
  };
};

module.exports = recorded;
